=== DiosaEstelaa/subidaNotaLM/ejercicio2/lopeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<xs:element name="nombre" type="xs:string"/>
<xs:element name="evaluacion" type="xs:string"/>
<xs:element name="nota" type="xs:integer"/>

<!-- definimos alumno-->
<xs:complexType name="tipoAlumno">
    <xs:sequence>
        <xs:element name="nombre" minOccurs="1">
            <xs:simpleType>
                <xs:restriction base="xs:string"></xs:restriction>
            </xs:simpleType>
        </xs:element>

        <xs:element name="tlf">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{9}"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>

        <xs:element name="asignatura" minOccurs="0" maxOccurs="9">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="nombre"  minOccurs="1"/>
                    <xs:element name="evaluacion" />
                    <xs:element name="nota"  minOccurs="1"/>
                </xs:sequence>
                </xs:complexType>
        </xs:element>


    </xs:sequence>
</xs:complexType>

<!-- definimos grupo -->


<!-- definimos lope - estructura general-->

<xs:element name="lope">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Grupo" >
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre"  minOccurs="0"/>
                        <xs:element name="nivelEducativo" minOccurs="1" >
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" minOccurs="1"/>
                                    <xs:element name="alumno" type="tipoAlumno"  />
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>



</xs:schema>

=== DiosaEstelaa/subidaNotaLM/ejercicio2/lope.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lope>

<lope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="lopeSchema.xsd">

    <Grupo>
        <nombre>DAW</nombre>
        <nivelEducativo>
            <nombre>segundo</nombre>
                <alumno>
                    <nombre>Marcos</nombre>
                    <tlf>123456789</tlf>
                    <asignatura>
                        <nombre>Sistemas informaticos</nombre>
                        <evaluacion>segunda</evaluacion>
                        <nota>5</nota>
                    </asignatura>
                </alumno>
                <alumno>
                    <nombre>Paco</nombre>
                    <tlf>123456782</tlf>
                    <asignatura>
                        <nombre>Bases de Datps</nombre>
                        <evaluacion>tercera</evaluacion>
                        <nota>7</nota>
                    </asignatura>
                </alumno>
        </nivelEducativo>
    </Grupo>

    <Grupo>
        <nombre>ASIR</nombre>
        <nivelEducativo>
            <nombre>segundo</nombre>
                <alumno>
                    <nombre>Pepa</nombre>
                    <tlf>123456788</tlf>
                    <asignatura>
                        <nombre>Programacion</nombre>
                        <evaluacion>primera</evaluacion>
                        <nota>6</nota>
                    </asignatura>
                </alumno>
        </nivelEducativo>
    </Grupo>

</lope>

=== DiosaEstelaa/subidaNotaLM/ejercicio2/lopeInvalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lope>

<lope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="lopeSchema.xsd">



    <Grupo>
        <nombre>@$ยก4</nombre>
        <nivelEducativo>
            <nombre>segundo</nombre>
                <alumno>
                    <tlf>123456788</tlf>
                    <asignatura>
                        <nombre>Programacion</nombre>
                        <evaluacion>primera</evaluacion>
                        <nota>7896</nota>
                    </asignatura>
                </alumno>
        </nivelEducativo>
    </Grupo>

</lope>
